/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package kotlin.backend.guides.app

class MessageUtils {
    companion object {
        fun getMessage(): String = "Hello      World!"
    }
}
